### ISSUE TITLE
seal_config for custom data

### ISSUE THREAD

**Issue by yankeesong** [windingwind/seal-3d#1]
Hi,

Thanks for the great work!
I'm trying to use this for my custom capture. May I ask how shall I obtain the seal_config file for my custom data? Thanks!

**Comment by windingwind** [comment]
In the published version, we have a GUI for some of the editing types. When you run editing via GUI, the `seal_config.json` is generated.

Otherwise, you will need to write a script to generate the config file from your user input. The parameters of the config can be found in `seal_utils.py`. Take the `SealBBoxMapper `, aka bounding shape editing, as an example:

https://github.com/windingwind/seal-3d/blob/e61370608238de74ccbdb323cc0e78806fa8f881/SealNeRF/seal_utils.py#L156-L166

**Comment by windingwind** [comment]
And please note that the original NGP implementation which we are based on does not perform well on real-captured data. The Nerfacto of Nerf Studio can be a good base, but we didn't use that from the beginning.

We welcome anyone who is interested in transplanting our implementation to Nerf Studio: https://github.com/nerfstudio-project/nerfstudio

**Comment by yankeesong** [comment]
Got it. Now I'm trying the GUI. In brush mode, I followed the video on the project page, but the the error "ValueError: The array must not be empty." In anchor mode I got ValueError: The points must not be collinear.". Do you have any idea how this happened? I am using the Lego scene and I just made a brush and clicked "train". Is there anything else I should do?

**Comment by windingwind** [comment]
Where are these errors thrown from? We need the full output to locate the problem.

**Comment by yankeesong** [comment]
Here's the step-by-step breakdown of what I did:

Scirpt:
python main_SealNeRF.py data/lego/\
    --workspace exps/lego_bbox -O --bound 1.0 --scale 0.8 --dt_gamma 0\
    --pretraining_epochs 100 --extra_epochs 150\
    --pretraining_local_point_step 0.005 --pretraining_surrounding_point_step -1\
    --pretraining_lr 0.05 --ckpt exps/lego/checkpoints/ngp_ep0150.pth\
    --teacher_workspace exps/lego --teacher_ckpt exps/lego/checkpoints/ngp_ep0150.pth\
    --seal_config data/seal/lego_bbox/\
    --eval_interval 100 --eval_count 10 --gui

GUI operations:
anchor - select - select anchor on the image
train - start

Then I got the following error:
Traceback (most recent call last):
  File "/home/ryanrzzhang/文档/yankesong/seal-3d/SealNeRF/gui.py", line 483, in callback_train
    self.trainer.model.init_mapper(self.opt.workspace, self.config)
  File "/home/ryanrzzhang/文档/yankesong/seal-3d/SealNeRF/renderer.py", line 23, in init_mapper
    self.seal_mapper = get_seal_mapper(config_dir, config_dict, config_file)
  File "/home/ryanrzzhang/文档/yankesong/seal-3d/SealNeRF/seal_utils.py", line 582, in get_seal_mapper
    return SealAnchorMapper(config_path, config_dict)
  File "/home/ryanrzzhang/文档/yankesong/seal-3d/SealNeRF/seal_utils.py", line 474, in __init__
    plane = Plane.best_fit(seal_config['raw'])
  File "/home/ryanrzzhang/anaconda3/envs/seal3D/lib/python3.10/site-packages/skspatial/objects/plane.py", line 676, in best_fit
    raise ValueError("The points must not be collinear.")
ValueError: The points must not be collinear.

**Comment by windingwind** [comment]
That's it - you might be clicking the same point 3 times.

To construct a plane for anchor, the input points must not be collinear, as the error says.

**Comment by yankeesong** [comment]
Thanks!
