### ISSUE TITLE
Instant NGP false

### ISSUE THREAD

**Issue by xiyufeng2** [windingwind/seal-3d#2]
I train the Instant NGP model with 360_v2 dataset， but the PSNR is low to 10。Can you afford 1 or 2 pretrained model with your dataset ？Thank you very much！email : 496598212@qq.com

**Comment by xiyufeng2** [comment]
It also faied with my own data processed with colmap ,which the PSNR is low to 10. But high to 22 with the synthetic data。Is there any training skills？

**Comment by windingwind** [comment]
Sorry, we don't have any checkpoints for the 360 dataset. Our experiments are mostly on Blender and DTU.

If you have any issue with the dataset, please report to the author of the base repo: [ashawkey/torch-ngp](https://github.com/ashawkey/torch-ngp). We could not provide further help with this.
